### ISSUE TITLE
Add unit test for "PARAMETER_INSERT" change type

### ISSUE THREAD

**Issue by zekimazan** [zekimazan/changedistiller#24]
- Test files should be under the "/resources/testdata/src_changetypes/" directory.
- Write your unit test code under the "ch.uzh.ifi.seal.changedistiller.unittest" package.

**Comment by muzafferbugra** [comment]
+

**Comment by canberksakarya** [comment]
Hocam proje ile ilgili doldurulması gereken form gereği burada bu issue nun bana atandığını ve benim aldığımı onaylıyorum.
