### ISSUE TITLE
Add unit test for "REMOVED_OBJECT_STATE" change type

### ISSUE THREAD

**Issue by zekimazan** [zekimazan/changedistiller#36]
- Test files should be under the "/resources/testdata/src_changetypes/" directory.
- Write your unit test code under the "ch.uzh.ifi.seal.changedistiller.unittest" package.

**Comment by cagdasgerede** [comment]
@zekimazan 
Zeki, Gizem Uyaniker pull request gonderdi mi? @guyaniker

**Comment by zekimazan** [comment]
https://github.com/zekimazan/changedistiller/pull/72

2018-04-08 17:32 GMT+03:00 Cagdas Evren Gerede <notifications@github.com>:
